In [11]:
import pandas as pd
import numpy as np

In [61]:
data = pd.read_excel('./data/interim/field_data_coarse_clean.xlsx')

data.head()

/Users/robertcollar/miniconda3/envs/EPSC-552-Mont-St-Hilaire/lib/python3.9/site-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

,wkt_geom,UTM-EW,UTM-NS,Group,Date,Weather,SampleID,Type,River order,Discharge,...,EC (uS/cm),T(C),Type Sed,Land use,Disturbance,Duplicate,Photo no.,Comments,lineNS,lineEW
0,Point,643901.071880,5.044402e+06,1,2021-09-24,Rain,GR1-001,Soil,NaN,NaN,...,NaN,NaN,NaN,ForEST,Yes,NaN,NaN,Near Trail,10,NaN
1,Point,643858.740795,5.044593e+06,1,2021-09-24,Rain,GR1-002,Soil,NaN,NaN,...,NaN,NaN,NaN,FOREST,No,NaN,NaN,On Slope,10,4
2,Point,643873.996064,5.044791e+06,1,2021-09-24,Rain,GR1-003,Soil,NaN,NaN,...,NaN,NaN,NaN,Forest,Yes,NaN,NaN,Up Slope From Trail,10,5
3,Point,643709.451179,5.044921e+06,1,2021-09-24,Rain,GR1-W01,Sediment,2.0,NaN,...,NaN,NaN,Clay,Forest,Yes,NaN,GR1-WP1,Upstream Of And Near Drainage Under Trail,9-10,5-6
4,Point,643877.208886,5.045003e+06,1,2021-09-24,Rain,GR1-004,Soil,NaN,NaN,...,NaN,NaN,NaN,Forest,No,NaN,NaN,NaN,10,6

In [63]:
## make all characters lowercase for a subset of fields
lower_case_fields = ["Weather", "Type", "Type Sed", "Land use", "Disturbance", "Comments", "lineNS", "lineEW"]
for field in lower_case_fields: 
    data[field] = data[field].str.lower()

In [64]:
## remove unnecessary data from "Duplicate" field
data["Duplicate"] = data["Duplicate"].replace("No", np.NaN)
data["Duplicate"] = data["Duplicate"].replace("Yes", np.NaN)

In [65]:
## Remove NS and EW prefixes from "lineNS" and "lineEW" fields respectively; remove leading 0
data["lineNS"] = data["lineNS"].map(lambda x: str(x).lstrip("ns"))
data["lineNS"] = data["lineNS"].map(lambda x: str(x).lstrip("0"))

data["lineEW"] = data["lineEW"].map(lambda x: str(x).lstrip("ew"))
data["lineEW"] = data["lineEW"].map(lambda x: str(x).lstrip("0"))

In [66]:
data.head()

,wkt_geom,UTM-EW,UTM-NS,Group,Date,Weather,SampleID,Type,River order,Discharge,...,EC (uS/cm),T(C),Type Sed,Land use,Disturbance,Duplicate,Photo no.,Comments,lineNS,lineEW
0,Point,643901.071880,5.044402e+06,1,2021-09-24,rain,GR1-001,soil,NaN,NaN,...,NaN,NaN,NaN,forest,yes,NaN,NaN,near trail,10,nan
1,Point,643858.740795,5.044593e+06,1,2021-09-24,rain,GR1-002,soil,NaN,NaN,...,NaN,NaN,NaN,forest,no,NaN,NaN,on slope,10,4
2,Point,643873.996064,5.044791e+06,1,2021-09-24,rain,GR1-003,soil,NaN,NaN,...,NaN,NaN,NaN,forest,yes,NaN,NaN,up slope from trail,10,5
3,Point,643709.451179,5.044921e+06,1,2021-09-24,rain,GR1-W01,sediment,2.0,NaN,...,NaN,NaN,clay,forest,yes,NaN,GR1-WP1,upstream of and near drainage under trail,9-10,5-6
4,Point,643877.208886,5.045003e+06,1,2021-09-24,rain,GR1-004,soil,NaN,NaN,...,NaN,NaN,NaN,forest,no,NaN,NaN,NaN,10,6

In [67]:
## Replace variations in "Land Use" field
data["Land use"] = data["Land use"].replace({"forested": "forest"})

In [68]:
data.head()

,wkt_geom,UTM-EW,UTM-NS,Group,Date,Weather,SampleID,Type,River order,Discharge,...,EC (uS/cm),T(C),Type Sed,Land use,Disturbance,Duplicate,Photo no.,Comments,lineNS,lineEW
0,Point,643901.071880,5.044402e+06,1,2021-09-24,rain,GR1-001,soil,NaN,NaN,...,NaN,NaN,NaN,forest,yes,NaN,NaN,near trail,10,nan
1,Point,643858.740795,5.044593e+06,1,2021-09-24,rain,GR1-002,soil,NaN,NaN,...,NaN,NaN,NaN,forest,no,NaN,NaN,on slope,10,4
2,Point,643873.996064,5.044791e+06,1,2021-09-24,rain,GR1-003,soil,NaN,NaN,...,NaN,NaN,NaN,forest,yes,NaN,NaN,up slope from trail,10,5
3,Point,643709.451179,5.044921e+06,1,2021-09-24,rain,GR1-W01,sediment,2.0,NaN,...,NaN,NaN,clay,forest,yes,NaN,GR1-WP1,upstream of and near drainage under trail,9-10,5-6
4,Point,643877.208886,5.045003e+06,1,2021-09-24,rain,GR1-004,soil,NaN,NaN,...,NaN,NaN,NaN,forest,no,NaN,NaN,NaN,10,6

In [58]:
data.to_excel('./data/interim/field_data_fine_clean.xlsx', 'field_data')